# Updated training configuration for Splicevo model

# Device configuration
device: cuda # "cuda" or "cpu"
cpu_threads: 8
cudnn_benchmark: true
gpu_memory_fraction: 0.5

# Data configuration
data:
  path: /home/elek/projects/splicing/results/data_processing/processed_data_train.npz
  use_mmap: true
  train_split: 0.8
  normalization_method: per_sample_cpm   # 'per_sample_cpm' or 'global'

# Model architecture
model:
  embed_dim: 128
  num_resblocks: 16
  dilation_strategy: alternating
  alternate: 4 
  num_classes: 3
  context_len: 450
  dropout: 0.4

# Training configuration
training:
  # Optimizer
  learning_rate: 1.0e-5
  weight_decay: 1.0e-3 
  
  # Loss weights
  splice_weight: 0.9
  usage_weight: 0.1

  # Class balancing
  use_class_weights: true
  
  # Training loop
  n_epochs: 100
  early_stopping_patience: 5
  
  # Memory optimization
  use_amp: true
  gradient_accumulation_steps: 4
  
  # DataLoader
  dataloader:
    batch_size: 64
    num_workers: 32
    prefetch_factor: 4

# Output configuration
output:
  checkpoint_dir: /home/elek/projects/splicing/results/models/brain
  use_tensorboard: true
